[video]
width = 2800
height = 1752
fps = 0
bitrate_kbps = 8000
encode_scale = 0.75
refresh_hz = 120
auto_bitrate = false

[input]
touch = true
pen = true
keyboard = true
pen_cursor = true

[output]
create = true
name = "MEGADISPLAY"
scale = 1.5

[ipc]
